#!/bin/bash
branch=${1:-master}
nextbranch=${branch}-next

for i in openembedded-core yocto-docs bitbake meta-poky; do
    echo $i
    if [ $branch != "master" -a $i = "bitbake" ]; then
        continue
    fi
    cd ~/oss/maint/$i
    git checkout $nextbranch
    git rebase $branch
done

cd ~/oss/stable/poky

layerfile=combo-layer-${branch}-next.conf

cp ../pokyconfig/$layerfile ../pokyconfig/combo-layer-next.conf
sed -i -e "s/${branch}/${nextbranch}/g" ../pokyconfig/combo-layer-next.conf
if [ $nextbranch = "thud-next" ]; then
    sed -i -z -e  "s/\(bitbake\nbranch = \)thud-next/\11.38/g" ../pokyconfig/combo-layer-next.conf
fi

git checkout $nextbranch
git reset $branch --hard
# Add -D option for debug
../pokyconfig/combo-layer -c ../pokyconfig/combo-layer-next.conf -n update
git checkout master
