#!/bin/bash
branch=${1:-master}
nextbranch=${branch}-next

for i in oe-core yocto-docs bitbake meta-yocto; do
    if [ $branch != "master" -a $i = "bitbake" ]; then
        continue
    fi
    cd ~/Repos/$i
    git checkout $nextbranch
    git rebase $branch
done

cd ~/Repos/poky

layerfile=combo-layer-${branch}.conf
if [ $branch = "master" ]; then
    layerfile=combo-layer.conf
fi
cp ../pokyconfig/$layerfile ../pokyconfig/combo-layer-next.conf
sed -i -e "s/${branch}/${nextbranch}/g" ../pokyconfig/combo-layer-next.conf
git checkout $nextbranch
git reset $branch --hard
# Add -D option for debug
../pokyconfig/combo-layer -c ../pokyconfig/combo-layer-next.conf -n update
git checkout master